#!/bin/sh
# Refuse to push if the rendered site has newly broken internal links.
# One-time activation on each machine:  git config core.hooksPath .githooks
cd "$(git rev-parse --show-toplevel)" && exec perl check_links.pl
